name: 'Terraform'

on:
  push:
    branches:
      - main
    paths:
      - '*.tf' 
  pull_request:
    branches:
      - main
    paths:
      - '*.tf'  
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '0.12.31'  # Update this to the version you are using

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_azure_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        TF_VAR_azure_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        TF_VAR_azure_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
