name: 'Terraform'

on:
  push:
    branches:
      - main
    paths:
      - '*.tf' 
  pull_request:
    branches:
      - main
    paths:
      - '*.tf'  
  workflow_dispatch:
    inputs:
      resources:
        description: 'Resources to import (format: type1=id1,type2=id2)'
        required: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '0.12.31'

    - name: Terraform Import Multiple Resources
      if: github.event.inputs.resources
      run: |
        IFS=',' read -ra ADDR <<< "${{ github.event.inputs.resources }}"
        for resource in "${ADDR[@]}"; do
          IFS='=' read -ra RES <<< "$resource"
          terraform import "${RES[0]}" "${RES[1]}"
        done
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
