name: 'Terraform'

on:
  push:
    branches:
      - main
    paths:
      - '*.tf'  # Assuming Terraform files are in the root with .tf extension
  pull_request:
    branches:
      - main
    paths:
      - '*.tf'  # Assuming Terraform files are in the root with .tf extension
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '0.12.24'  # Update this to the version you are using

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
